########## Testcase 0: Failed ##########
Expected Output: 
True

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:8)
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
False

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:8)
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
True

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:8)
----------------------------------------

########## Testcase 3: Failed ##########
Expected Output: 
True

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:8)
----------------------------------------

########## Testcase 4: Failed ##########
Expected Output: 
False

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:8)
----------------------------------------

########## Testcase 5: Failed ##########
Expected Output: 
False

Your Output: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Solution.main(Solution.java:8)
----------------------------------------

